resources:
- deployment.yaml
- route.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:917d0554044b25e2912ae7b7eabd352a77285a1f132edf5f5de8e24c8770ae55
  name: quay.io/adhis/argocd
  newName: quay.io/adhis/argocd
