resources:
- deployment.yaml
- route.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:0c0cfc8c75c1188370d14525fcd7e0f6a3f9174a11d5bc2588ceb26eb9e194a6
  name: quay.io/adhis/argocd
  newName: quay.io/adhis/argocd
