resources:
- deployment.yaml
- route.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b2ddfd416d7586175b5f9549123f18c761421c58bcd4a8a0d2b67dca8fabb9ed
  name: quay.io/adhis/argocd
  newName: quay.io/adhis/argocd
