resources:
- deployment.yaml
- route.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:c21cc70423a837b484303ef9b8e42a8cf2dced18dd5d5b973e165b7f532c601f
  name: quay.io/adhis/argocd
  newName: quay.io/adhis/argocd
