resources:
- deployment.yaml
- route.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:27b455aab4c22f69cc92b797b91064ea4ddc7ae86061999c72a034555132f7d3
  name: quay.io/adhis/argocd
  newName: quay.io/adhis/argocd
