
resources:
- deployment.yaml
- route.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/adhis/argocd
  newName: quay.io/adhis/argocd
- name: quay.io/adhis/java
  newName: quay.io/adhis/java
  newTag: 14656aba4986b3329b1d1a4ad0c001ad68192a0e
