
resources:
- deployment.yaml
- route.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/adhis/argocd
  newName: quay.io/adhis/argocd
  newTag: 
