resources:
- deployment.yaml
- route.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:997a106e46bdf52a624cb893e9cae51b038db245d3c6a630ace5cf61c9255f42
  name: quay.io/adhis/argocd
  newName: quay.io/adhis/argocd
